from __future__ import annotations

import math
import os
from pathlib import Path
from typing import Optional

import pandas as pd

try:
    from behavior import attach_zone_ids
except ModuleNotFoundError:
    from app.behavior import attach_zone_ids


def _meters_to_lat(meters: float) -> float:
    return meters / 111_320


def _meters_to_lon(meters: float, lat: float) -> float:
    return meters / (111_320 * max(math.cos(math.radians(lat)), 0.2))


class OracleRepository:
    def __init__(
        self,
        user: Optional[str] = None,
        password: Optional[str] = None,
        dsn: Optional[str] = None,
    ) -> None:
        self.user = user if user is not None else os.getenv("ORACLE_USER")
        self.password = password if password is not None else os.getenv("ORACLE_PASSWORD")
        self.dsn = dsn if dsn is not None else os.getenv("ORACLE_DSN")

    def configured(self) -> bool:
        return bool(self.user and self.password and self.dsn)

    def _connect(self):
        import oracledb

        return oracledb.connect(user=self.user, password=self.password, dsn=self.dsn)

    def test_connection(self) -> tuple[bool, str]:
        if not self.configured():
            return False, "Database settings are incomplete."
        try:
            with self._connect() as conn:
                with conn.cursor() as cur:
                    cur.execute("SELECT 1 FROM dual")
                    cur.fetchone()
            return True, "Connected successfully."
        except Exception as exc:  # noqa: BLE001
            return False, f"Connection failed: {exc}"

    def write_dataframe(self, df: pd.DataFrame, table_name: str) -> None:
        if not self.configured() or df.empty:
            return

        cols = list(df.columns)
        binds = ",".join([f":{i+1}" for i in range(len(cols))])
        sql = f"INSERT INTO {table_name} ({','.join(cols)}) VALUES ({binds})"

        records = [tuple(row) for row in df.itertuples(index=False, name=None)]
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.executemany(sql, records)
            conn.commit()

    def fetch_dataframe(self, sql: str) -> pd.DataFrame:
        if not self.configured():
            return pd.DataFrame()
        with self._connect() as conn:
            return pd.read_sql(sql, conn)

    def setup_converged_schema(self) -> None:
        statements = [
            """
            BEGIN
              FOR idx IN (
                SELECT index_name FROM user_indexes
                WHERE index_name IN ('RESTRICTED_ZONES_SHAPE_IDX', 'TRACKING_EVENTS_LOCATION_IDX')
              ) LOOP
                EXECUTE IMMEDIATE 'DROP INDEX ' || idx.index_name;
              END LOOP;
            EXCEPTION WHEN OTHERS THEN NULL; END;
            """,
            """
            BEGIN
              DELETE FROM user_sdo_geom_metadata
              WHERE table_name IN ('RESTRICTED_ZONES', 'TRACKING_EVENTS');
              COMMIT;
            EXCEPTION WHEN OTHERS THEN NULL; END;
            """,
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE subject_behavior_vectors PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE behavior_patterns PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE tracking_events PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE restricted_zones PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            """
            CREATE TABLE restricted_zones (
              zone_id NUMBER PRIMARY KEY,
              zone_name VARCHAR2(100) NOT NULL,
              zone_type VARCHAR2(40) NOT NULL,
              center_lat NUMBER(10,6) NOT NULL,
              center_lon NUMBER(10,6) NOT NULL,
              radius_m NUMBER(10,2) NOT NULL,
              shape MDSYS.SDO_GEOMETRY NOT NULL
            )
            """,
            """
            CREATE TABLE tracking_events (
              event_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
              participant_id VARCHAR2(30) NOT NULL,
              event_ts TIMESTAMP NOT NULL,
              city VARCHAR2(50),
              speed_kmh NUMBER(6,2),
              lat NUMBER(10,6) NOT NULL,
              lon NUMBER(10,6) NOT NULL,
              location MDSYS.SDO_GEOMETRY NOT NULL
            )
            """,
            """
            CREATE TABLE behavior_patterns (
              pattern_id NUMBER PRIMARY KEY,
              description VARCHAR2(100) NOT NULL,
              decision_hint VARCHAR2(30) NOT NULL,
              behavior_vector VECTOR(3, FLOAT32) NOT NULL
            )
            """,
            """
            CREATE TABLE subject_behavior_vectors (
              participant_id VARCHAR2(30) PRIMARY KEY,
              zone_id NUMBER NOT NULL,
              zone_name VARCHAR2(100) NOT NULL,
              inside_zone NUMBER(1) NOT NULL,
              speed_score NUMBER(8,6) NOT NULL,
              dwell_score NUMBER(8,6) NOT NULL,
              proximity_score NUMBER(8,6) NOT NULL,
              behavior_vector VECTOR(3, FLOAT32) NOT NULL,
              CONSTRAINT subject_behavior_vectors_zone_fk
                FOREIGN KEY (zone_id) REFERENCES restricted_zones(zone_id)
            )
            """,
            """
            INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
            VALUES (
              'RESTRICTED_ZONES',
              'SHAPE',
              MDSYS.SDO_DIM_ARRAY(
                MDSYS.SDO_DIM_ELEMENT('Longitude', -180, 180, 5),
                MDSYS.SDO_DIM_ELEMENT('Latitude', -90, 90, 5)
              ),
              8307
            )
            """,
            """
            INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
            VALUES (
              'TRACKING_EVENTS',
              'LOCATION',
              MDSYS.SDO_DIM_ARRAY(
                MDSYS.SDO_DIM_ELEMENT('Longitude', -180, 180, 5),
                MDSYS.SDO_DIM_ELEMENT('Latitude', -90, 90, 5)
              ),
              8307
            )
            """,
            "CREATE INDEX restricted_zones_shape_idx ON restricted_zones(shape) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2",
            "CREATE INDEX tracking_events_location_idx ON tracking_events(location) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2",
        ]
        with self._connect() as conn:
            with conn.cursor() as cur:
                for statement in statements:
                    cur.execute(statement)
            conn.commit()

    def _zone_polygon_ordinates(self, center_lat: float, center_lon: float, radius_m: float) -> list[float]:
        north = center_lat + _meters_to_lat(radius_m)
        south = center_lat - _meters_to_lat(radius_m)
        east = center_lon + _meters_to_lon(radius_m, center_lat)
        west = center_lon - _meters_to_lon(radius_m, center_lat)
        return [
            west, south,
            west, north,
            east, north,
            east, south,
            west, south,
        ]

    def load_converged_demo(
        self,
        locations: pd.DataFrame,
        rules: pd.DataFrame,
        patterns: pd.DataFrame,
        behavior_vectors: pd.DataFrame,
    ) -> None:
        if not self.configured():
            return

        rules = attach_zone_ids(rules)
        zone_rows = rules[["zone_id", "zone_name", "rule_type", "zone_lat", "zone_lon", "radius_m"]].drop_duplicates()

        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute("TRUNCATE TABLE subject_behavior_vectors")
                cur.execute("TRUNCATE TABLE behavior_patterns")
                cur.execute("TRUNCATE TABLE tracking_events")
                cur.execute("TRUNCATE TABLE restricted_zones")

                zone_sql = """
                    INSERT INTO restricted_zones (
                        zone_id, zone_name, zone_type, center_lat, center_lon, radius_m, shape
                    ) VALUES (
                        :1, :2, :3, :4, :5, :6,
                        MDSYS.SDO_GEOMETRY(
                            2003,
                            8307,
                            NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
                            MDSYS.SDO_ORDINATE_ARRAY(:7, :8, :9, :10, :11, :12, :13, :14, :15, :16)
                        )
                    )
                """
                zone_records = []
                for row in zone_rows.itertuples(index=False):
                    ordinates = self._zone_polygon_ordinates(float(row.zone_lat), float(row.zone_lon), float(row.radius_m))
                    zone_records.append(
                        (
                            int(row.zone_id),
                            row.zone_name,
                            row.rule_type,
                            float(row.zone_lat),
                            float(row.zone_lon),
                            float(row.radius_m),
                            *ordinates,
                        )
                    )
                cur.executemany(zone_sql, zone_records)

                tracking_sql = """
                    INSERT INTO tracking_events (
                        participant_id, event_ts, city, speed_kmh, lat, lon, location
                    ) VALUES (
                        :participant_id, :event_ts, :city, :speed_kmh, :lat, :lon,
                        MDSYS.SDO_GEOMETRY(
                            2001,
                            8307,
                            MDSYS.SDO_POINT_TYPE(:lon, :lat, NULL),
                            NULL,
                            NULL
                        )
                    )
                """
                tracking_records = [
                    {
                        "participant_id": row.participant_id,
                        "event_ts": row.event_ts.to_pydatetime() if hasattr(row.event_ts, 'to_pydatetime') else row.event_ts,
                        "city": row.city,
                        "speed_kmh": float(row.speed_kmh),
                        "lat": float(row.lat),
                        "lon": float(row.lon),
                    }
                    for row in locations.itertuples(index=False)
                ]
                cur.executemany(tracking_sql, tracking_records)

                pattern_sql = """
                    INSERT INTO behavior_patterns (pattern_id, description, decision_hint, behavior_vector)
                    VALUES (:1, :2, :3, TO_VECTOR(:4, 3, FLOAT32))
                """
                pattern_records = [
                    (int(row.pattern_id), row.description, row.decision_hint, row.behavior_vector)
                    for row in patterns.itertuples(index=False)
                ]
                cur.executemany(pattern_sql, pattern_records)

                subject_sql = """
                    INSERT INTO subject_behavior_vectors (
                        participant_id,
                        zone_id,
                        zone_name,
                        inside_zone,
                        speed_score,
                        dwell_score,
                        proximity_score,
                        behavior_vector
                    ) VALUES (
                        :1, :2, :3, :4, :5, :6, :7, TO_VECTOR(:8, 3, FLOAT32)
                    )
                """
                subject_records = [
                    (
                        row.participant_id,
                        int(row.zone_id),
                        row.zone_name,
                        int(row.inside_zone),
                        float(row.speed_score),
                        float(row.dwell_score),
                        float(row.proximity_score),
                        row.behavior_vector,
                    )
                    for row in behavior_vectors.itertuples(index=False)
                ]
                cur.executemany(subject_sql, subject_records)
            conn.commit()

    def run_hybrid_decisions(self) -> pd.DataFrame:
        sql = """
            WITH matched AS (
              SELECT
                sbv.participant_id,
                sbv.zone_name,
                bp.description AS matched_pattern,
                bp.decision_hint,
                ROUND(VECTOR_DISTANCE(sbv.behavior_vector, bp.behavior_vector, COSINE), 6) AS similarity_score,
                sbv.speed_score,
                sbv.dwell_score,
                sbv.proximity_score,
                sbv.inside_zone,
                ROW_NUMBER() OVER (
                  PARTITION BY sbv.participant_id
                  ORDER BY VECTOR_DISTANCE(sbv.behavior_vector, bp.behavior_vector, COSINE)
                ) AS rn
              FROM subject_behavior_vectors sbv
              CROSS JOIN behavior_patterns bp
            )
            SELECT
              participant_id,
              zone_name,
              CASE WHEN inside_zone = 0 THEN 'N/A' ELSE matched_pattern END AS matched_pattern,
              CASE
                WHEN inside_zone = 0 THEN 'NO_ACTION'
                WHEN decision_hint = 'DEPRIORITIZE' AND similarity_score <= 0.08 THEN 'DEPRIORITIZE'
                WHEN decision_hint = 'ELEVATE' AND similarity_score <= 0.20 THEN 'ELEVATE'
                ELSE 'REVIEW'
              END AS decision,
              CASE WHEN inside_zone = 0 THEN NULL ELSE similarity_score END AS similarity_score,
              speed_score,
              dwell_score,
              proximity_score
            FROM matched
            WHERE rn = 1
            ORDER BY participant_id
        """
        return self.fetch_dataframe(sql)

    def has_converged_schema(self) -> bool:
        sql = """
            SELECT COUNT(*) AS object_count
            FROM user_tables
            WHERE table_name IN (
              'RESTRICTED_ZONES',
              'TRACKING_EVENTS',
              'BEHAVIOR_PATTERNS',
              'SUBJECT_BEHAVIOR_VECTORS'
            )
        """
        df = self.fetch_dataframe(sql)
        if df.empty:
            return False
        return int(df.iloc[0]["OBJECT_COUNT"]) == 4

    def script_text(self, relative_path: str) -> str:
        return Path(relative_path).read_text()
