WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
  FOR idx IN (
    SELECT index_name FROM user_indexes
    WHERE index_name IN ('RESTRICTED_ZONES_SHAPE_IDX', 'TRACKING_EVENTS_LOCATION_IDX')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP INDEX ' || idx.index_name;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  DELETE FROM user_sdo_geom_metadata
  WHERE table_name IN ('RESTRICTED_ZONES', 'TRACKING_EVENTS');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE subject_behavior_vectors PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE behavior_patterns PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tracking_events PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE restricted_zones PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE restricted_zones (
  zone_id NUMBER PRIMARY KEY,
  zone_name VARCHAR2(100) NOT NULL,
  zone_type VARCHAR2(40) NOT NULL,
  center_lat NUMBER(10,6) NOT NULL,
  center_lon NUMBER(10,6) NOT NULL,
  radius_m NUMBER(10,2) NOT NULL,
  shape MDSYS.SDO_GEOMETRY NOT NULL
);

CREATE TABLE tracking_events (
  event_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  participant_id VARCHAR2(30) NOT NULL,
  event_ts TIMESTAMP NOT NULL,
  city VARCHAR2(50),
  speed_kmh NUMBER(6,2),
  lat NUMBER(10,6) NOT NULL,
  lon NUMBER(10,6) NOT NULL,
  location MDSYS.SDO_GEOMETRY NOT NULL
);

CREATE TABLE behavior_patterns (
  pattern_id NUMBER PRIMARY KEY,
  description VARCHAR2(100) NOT NULL,
  decision_hint VARCHAR2(30) NOT NULL,
  behavior_vector VECTOR(3, FLOAT32) NOT NULL
);

CREATE TABLE subject_behavior_vectors (
  participant_id VARCHAR2(30) PRIMARY KEY,
  zone_id NUMBER NOT NULL,
  zone_name VARCHAR2(100) NOT NULL,
  inside_zone NUMBER(1) NOT NULL,
  speed_score NUMBER(8,6) NOT NULL,
  dwell_score NUMBER(8,6) NOT NULL,
  proximity_score NUMBER(8,6) NOT NULL,
  behavior_vector VECTOR(3, FLOAT32) NOT NULL,
  CONSTRAINT subject_behavior_vectors_zone_fk
    FOREIGN KEY (zone_id) REFERENCES restricted_zones(zone_id)
);

INSERT INTO user_sdo_geom_metadata (
  table_name,
  column_name,
  diminfo,
  srid
) VALUES (
  'RESTRICTED_ZONES',
  'SHAPE',
  MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('Longitude', -180, 180, 5),
    MDSYS.SDO_DIM_ELEMENT('Latitude', -90, 90, 5)
  ),
  8307
);

INSERT INTO user_sdo_geom_metadata (
  table_name,
  column_name,
  diminfo,
  srid
) VALUES (
  'TRACKING_EVENTS',
  'LOCATION',
  MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('Longitude', -180, 180, 5),
    MDSYS.SDO_DIM_ELEMENT('Latitude', -90, 90, 5)
  ),
  8307
);

CREATE INDEX restricted_zones_shape_idx
  ON restricted_zones(shape)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX tracking_events_location_idx
  ON tracking_events(location)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

COMMIT;
