CREATE TABLE LOCATION_EVENTS (
  PARTICIPANT_ID VARCHAR2(30) NOT NULL,
  CITY VARCHAR2(50),
  EVENT_TS TIMESTAMP NOT NULL,
  LAT NUMBER(10,6) NOT NULL,
  LON NUMBER(10,6) NOT NULL,
  SPEED_KMH NUMBER(6,2)
);

CREATE TABLE DEVICE_EVENTS (
  PARTICIPANT_ID VARCHAR2(30) NOT NULL,
  EVENT_TS TIMESTAMP NOT NULL,
  BATTERY_PCT NUMBER(5,2),
  TAMPER_FLAG NUMBER(1),
  NO_SIGNAL_FLAG NUMBER(1)
);

CREATE TABLE RULES_SCHEDULES (
  PARTICIPANT_ID VARCHAR2(30) NOT NULL,
  RULE_TYPE VARCHAR2(40) NOT NULL,
  ZONE_NAME VARCHAR2(100),
  ZONE_LAT NUMBER(10,6),
  ZONE_LON NUMBER(10,6),
  RADIUS_M NUMBER(8,2)
);

CREATE TABLE ALERTS (
  PARTICIPANT_ID VARCHAR2(30) NOT NULL,
  EVENT_TS TIMESTAMP NOT NULL,
  ALERT_TYPE VARCHAR2(40) NOT NULL,
  SEVERITY VARCHAR2(10) NOT NULL,
  DETAILS VARCHAR2(1000)
);

CREATE TABLE RISK_SCORES (
  PARTICIPANT_ID VARCHAR2(30) NOT NULL,
  RISK_SCORE NUMBER(10,2) NOT NULL,
  RISK_BAND VARCHAR2(10) NOT NULL
);

CREATE INDEX IX_LOC_EVENTS_TS ON LOCATION_EVENTS (EVENT_TS);
CREATE INDEX IX_ALERTS_TS ON ALERTS (EVENT_TS);
CREATE INDEX IX_ALERTS_PARTICIPANT ON ALERTS (PARTICIPANT_ID);
